# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Albertsons-Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Albertsons-Assignment
  pod 'Alamofire'

  target 'Albertsons-AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Albertsons-AssignmentUITests' do
    # Pods for testing
  end

end
